spring:
  application:
    name: graphql-application

  datasource:
    url: jdbc:postgresql://${IP_DATABASE:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  graphql:
    path: /graphql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080